import type { LucideIcon } from "lucide-react";
import {
  Anchor,
  Baby,
  BadgePercent,
  Bath,
  BedDouble,
  Bike,
  BookOpen,
  Box,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Bus,
  Cable,
  Camera,
  Car,
  CarFront,
  Cat,
  ChefHat,
  CircleParking,
  ClipboardList,
  Construction,
  Cpu,
  Disc,
  Dog,
  DoorOpen,
  Drill,
  Droplets,
  Dumbbell,
  Fan,
  FileText,
  Film,
  Flame,
  Flower2,
  Focus,
  Footprints,
  Gamepad2,
  Gauge,
  Gem,
  Hammer,
  Headphones,
  HeartHandshake,
  Home,
  Hotel,
  Image,
  KeyRound,
  LandPlot,
  Laptop,
  Leaf,
  Lightbulb,
  MapPin,
  Mic2,
  Monitor,
  Moon,
  Mountain,
  Mouse,
  Music,
  Package,
  PaintBucket,
  Palette,
  PawPrint,
  PenTool,
  Phone,
  PiggyBank,
  Printer,
  Puzzle,
  Radio,
  Refrigerator,
  Scan,
  Scissors,
  Settings2,
  Shirt,
  Shovel,
  ShoppingBag,
  Smartphone,
  Snowflake,
  Sofa,
  Sparkles,
  Sprout,
  Stethoscope,
  Store,
  Sun,
  Tablet,
  Tag,
  Tent,
  TentTree,
  Trees,
  Truck,
  Tv,
  UserCog,
  Users,
  Wind,
  Van,
  Warehouse,
  WashingMachine,
  Watch,
  Waves,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";

type Rule = { match: (s: string) => boolean; Icon: LucideIcon };

/** Reguli în ordinea specificității (primele au prioritate). */
const RULES: Rule[] = [
  { match: (s) => s.includes("autoturism") || s.includes("epoca"), Icon: Car },
  { match: (s) => s.includes("microbuz") || s.includes("furgon"), Icon: Van },
  { match: (s) => s.includes("camion"), Icon: Truck },
  { match: (s) => s.includes("autobuz"), Icon: Bus },
  { match: (s) => s.includes("motocic") || s.includes("scuter") || s.includes("biciclete") || s.includes("trotinet"), Icon: Bike },
  { match: (s) => s.includes("atv"), Icon: CarFront },
  { match: (s) => s.includes("barci") || s.includes("ambarcat"), Icon: Anchor },
  { match: (s) => s.includes("electrice") && s.includes("transport"), Icon: Zap },
  { match: (s) => s.includes("tehnica-agricol") || s.includes("tractor") || s.includes("cositoare"), Icon: Construction },
  { match: (s) => s.includes("tehnica-speciala") || s.includes("constructii-mech"), Icon: Construction },
  { match: (s) => s.includes("remorci") || s.includes("rulot"), Icon: Truck },
  { match: (s) => s.includes("anvelope") || s.includes("vulcanizare"), Icon: CircleParking },
  { match: (s) => s.includes("piese-motor"), Icon: Gauge },
  { match: (s) => s.includes("piese-transmisie"), Icon: Settings2 },
  { match: (s) => s.includes("piese-frane"), Icon: Disc },
  { match: (s) => s.includes("piese-suspensie"), Icon: Wrench },
  { match: (s) => s.includes("piese-electrice") || s.includes("instalatie") || (s.includes("electrica") && !s.includes("job")), Icon: Zap },
  { match: (s) => s.includes("piese-caroserie") || s.includes("caroserie-acc"), Icon: DoorOpen },
  { match: (s) => s.includes("filtre") || s.includes("ulei"), Icon: Droplets },
  { match: (s) => s.includes("acc-salon") || s.includes("covoras"), Icon: Sofa },
  { match: (s) => s.includes("vopsea") && s.includes("transport"), Icon: PaintBucket },
  { match: (s) => s.includes("ajutor-tehnic") || s.includes("tractar"), Icon: Truck },
  { match: (s) => s.includes("chei") || s.includes("cricuri"), Icon: Wrench },
  { match: (s) => s.includes("compresoare"), Icon: Fan },
  { match: (s) => s.includes("diagnostic"), Icon: Scan },
  { match: (s) => s.includes("autoservice") || s.includes("reparatii-auto"), Icon: Wrench },
  { match: (s) => s.includes("transport-marfa") || s.includes("livrare"), Icon: Package },
  { match: (s) => s.includes("inchirieri"), Icon: KeyRound },
  { match: (s) => s.includes("spalatorie") || s.includes("sampon-auto"), Icon: Droplets },
  { match: (s) => s.includes("detergenti") || s.includes("ceara") && s.includes("transport"), Icon: Sparkles },
  { match: (s) => s.includes("smartphone"), Icon: Smartphone },
  { match: (s) => s.includes("telefoane-clasice"), Icon: Phone },
  { match: (s) => s.includes("tablete"), Icon: Tablet },
  { match: (s) => s.includes("smartwatch"), Icon: Watch },
  { match: (s) => s.includes("accesorii-tel"), Icon: Cable },
  { match: (s) => s.includes("laptop"), Icon: Laptop },
  { match: (s) => s.includes("pc-birou"), Icon: Monitor },
  { match: (s) => s.includes("monitoare"), Icon: Monitor },
  { match: (s) => s.includes("componente"), Icon: Cpu },
  { match: (s) => s.includes("periferice"), Icon: Mouse },
  { match: (s) => s.includes("retea"), Icon: Wifi },
  { match: (s) => s.includes("imprimante"), Icon: Printer },
  { match: (s) => s.includes("aparate-foto"), Icon: Camera },
  { match: (s) => s.includes("obiective"), Icon: Focus },
  { match: (s) => s.includes("drona"), Icon: Radio },
  { match: (s) => s.includes("casti") || s.includes("playere"), Icon: Headphones },
  { match: (s) => s.includes("console") || s.includes("jocuri"), Icon: Gamepad2 },
  { match: (s) => s.includes("bucatarie") && s.includes("electronice"), Icon: Refrigerator },
  { match: (s) => s.includes("ingrijire") && s.includes("electronice"), Icon: Bath },
  { match: (s) => s.includes("aspiratoare"), Icon: Wind },
  { match: (s) => s.includes("apartamente"), Icon: Building2 },
  { match: (s) => s.includes("garsoniere") || (s.includes("camere") && s.includes("imob")), Icon: BedDouble },
  { match: (s) => s.includes("case-") || (s.includes("case") && s.includes("imob")), Icon: Home },
  { match: (s) => s.includes("teren"), Icon: LandPlot },
  { match: (s) => s.includes("birouri") && s.includes("imob"), Icon: Building2 },
  { match: (s) => s.includes("spatii-comerciale"), Icon: Store },
  { match: (s) => s.includes("depozite") && s.includes("imob"), Icon: Warehouse },
  { match: (s) => s.includes("hoteluri"), Icon: Hotel },
  { match: (s) => s.includes("garaj") || (s.includes("parcare") && s.includes("imob")), Icon: CircleParking },
  { match: (s) => s.includes("agentii"), Icon: Users },
  { match: (s) => s.includes("evaluari"), Icon: ClipboardList },
  { match: (s) => s.includes("design-interior"), Icon: Palette },
  { match: (s) => s.includes("canapele") || s.includes("dormitor") || (s.includes("mobila") && s.includes("casa")), Icon: Sofa },
  { match: (s) => s.includes("bucatarie-mob"), Icon: ChefHat },
  { match: (s) => s.includes("birou-mob"), Icon: Briefcase },
  { match: (s) => s.includes("depozitare"), Icon: Package },
  { match: (s) => s.includes("materiale"), Icon: Box },
  { match: (s) => s.includes("unelte") && !s.includes("gradina"), Icon: Drill },
  { match: (s) => s.includes("sanitare"), Icon: Bath },
  { match: (s) => s.includes("gips-carton"), Icon: Hammer },
  { match: (s) => s.includes("mobilier-gradina") || s.includes("unelte-gradina"), Icon: Shovel },
  { match: (s) => s.includes("gratar"), Icon: Flame },
  { match: (s) => s.includes("perdele") || s.includes("covor"), Icon: Image },
  { match: (s) => s.includes("luminat"), Icon: Lightbulb },
  { match: (s) => s.includes("zugrav") || s.includes("faianta"), Icon: PaintBucket },
  { match: (s) => s.includes("montaj"), Icon: Hammer },
  { match: (s) => s.includes("site-uri") || s.includes("grafica"), Icon: FileText },
  { match: (s) => s.includes("reparatii-pc"), Icon: Laptop },
  { match: (s) => s.includes("coafor") || s.includes("cosmetic"), Icon: Scissors },
  { match: (s) => s.includes("masaj"), Icon: HeartHandshake },
  { match: (s) => s.includes("curatenie"), Icon: Sparkles },
  { match: (s) => s.includes("spalatorie-textile"), Icon: WashingMachine },
  { match: (s) => s.includes("meditatii") || (s.includes("cursuri") && s.includes("servicii")), Icon: BookOpen },
  { match: (s) => s.includes("foto-video"), Icon: Film },
  { match: (s) => s.includes("evenimente") && s.includes("muzica"), Icon: Mic2 },
  { match: (s) => s.includes("haine") && s.includes("moda"), Icon: Shirt },
  { match: (s) => s.includes("incalt"), Icon: Footprints },
  { match: (s) => s.includes("accesorii") && s.includes("moda"), Icon: ShoppingBag },
  { match: (s) => s.includes("greutati"), Icon: Dumbbell },
  { match: (s) => s.includes("fotbal"), Icon: Disc },
  { match: (s) => s.includes("tenis"), Icon: Disc },
  { match: (s) => s.includes("sporturi-iarna"), Icon: Snowflake },
  { match: (s) => s.includes("corturi"), Icon: Tent },
  { match: (s) => s.includes("drumetii"), Icon: Mountain },
  { match: (s) => s.includes("numismatica"), Icon: BadgePercent },
  { match: (s) => s.includes("machete"), Icon: Puzzle },
  { match: (s) => s.includes("caini"), Icon: Dog },
  { match: (s) => s.includes("pisici"), Icon: Cat },
  { match: (s) => s.includes("pasari") || s.includes("rozatoare"), Icon: Bug },
  { match: (s) => s.includes("flori") || s.includes("pomi"), Icon: Flower2 },
  { match: (s) => s.includes("dresaj"), Icon: PawPrint },
  { match: (s) => s.includes("vet"), Icon: Stethoscope },
  { match: (s) => s.includes("furaje") || s.includes("seminte"), Icon: Sprout },
  { match: (s) => s.includes("vite") || s.includes("oi") || s.includes("porci"), Icon: PiggyBank },
  { match: (s) => s.includes("carucior") || s.includes("scaun-auto"), Icon: Baby },
  { match: (s) => s.includes("jucarii"), Icon: Puzzle },
  { match: (s) => s.includes("carti-copii"), Icon: BookOpen },
  { match: (s) => s.includes("biberoane"), Icon: Baby },
  { match: (s) => s.includes("instrumente") && s.includes("muzica"), Icon: Music },
  { match: (s) => s.includes("echipament-studio"), Icon: Radio },
  { match: (s) => s.includes("tablouri"), Icon: Image },
  { match: (s) => s.includes("handmade"), Icon: PenTool },
  { match: (s) => s.includes("ceasuri"), Icon: Watch },
  { match: (s) => s.includes("bijuterii"), Icon: Gem },
  { match: (s) => s.includes("nedefinit"), Icon: Tag },
  { match: (s) => s.includes("linii-productie"), Icon: Settings2 },
  { match: (s) => s.includes("generatoare"), Icon: Zap },
  { match: (s) => s.includes("stocuri"), Icon: Package },
  { match: (s) => s.includes("administrativ"), Icon: ClipboardList },
  { match: (s) => s.includes("vanzari") && s.includes("job"), Icon: ShoppingBag },
  { match: (s) => s.includes("it-job"), Icon: Laptop },
  { match: (s) => s.includes("contabilitate"), Icon: FileText },
  { match: (s) => s.includes("operator") && s.includes("job"), Icon: Settings2 },
  { match: (s) => s.includes("sofer-job") || (s.includes("soferi") && s.includes("servicii")), Icon: Car },
  { match: (s) => s.includes("depozit") && s.includes("job"), Icon: Warehouse },
  { match: (s) => s.includes("horeca"), Icon: ChefHat },
  { match: (s) => s.includes("retail") && s.includes("job"), Icon: Store },
  { match: (s) => s.includes("ingrijire") && s.includes("servicii-job"), Icon: Users },
  { match: (s) => s.includes("zugrav-job"), Icon: PaintBucket },
  { match: (s) => s.includes("electrician-job"), Icon: Zap },
];

export function getSubcategoryLucideIcon(slug: string): LucideIcon {
  const s = slug.toLowerCase();
  for (const { match, Icon } of RULES) {
    if (match(s)) return Icon;
  }
  return Tag;
}
