import type { LucideIcon } from "lucide-react";
import {
  Anchor,
  Baby,
  BadgePercent,
  Bath,
  BedDouble,
  Bike,
  BookOpen,
  Box,
  Briefcase,
  Bug,
  Building2,
  Bus,
  Cable,
  Camera,
  Car,
  CarFront,
  Cat,
  ChefHat,
  CircleParking,
  ClipboardList,
  Construction,
  Cpu,
  Disc,
  Dog,
  DoorOpen,
  Drill,
  Droplets,
  Dumbbell,
  Fan,
  FileText,
  Film,
  Flame,
  Flower2,
  Focus,
  Footprints,
  Gamepad2,
  Gauge,
  Gem,
  Hammer,
  HardDrive,
  Headphones,
  HeartHandshake,
  Home,
  Hotel,
  Image,
  KeyRound,
  LandPlot,
  Laptop,
  Lightbulb,
  Megaphone,
  Mic2,
  Monitor,
  Mountain,
  Mouse,
  Music,
  Package,
  PaintBucket,
  Palette,
  PawPrint,
  PenTool,
  Phone,
  PiggyBank,
  Printer,
  Puzzle,
  Radio,
  Refrigerator,
  Scan,
  Scissors,
  Settings2,
  Shirt,
  Shovel,
  ShoppingBag,
  Smartphone,
  Snowflake,
  Sofa,
  Sparkles,
  Sprout,
  Stethoscope,
  Store,
  Tablet,
  Tag,
  Ticket,
  Tent,
  Truck,
  Tv,
  Users,
  Wind,
  Van,
  Warehouse,
  WashingMachine,
  Watch,
  Waves,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";

type Rule = { match: (s: string) => boolean; Icon: LucideIcon };

/** Reguli în ordinea specificității (primele au prioritate). */
const RULES: Rule[] = [
  { match: (s) => s.includes("electronice-ebook"), Icon: BookOpen },
  { match: (s) => s.includes("servere") && s.includes("electronice"), Icon: Cpu },
  { match: (s) => s.includes("electronice-nas"), Icon: HardDrive },
  { match: (s) => s.includes("camere-video") && s.includes("electronice"), Icon: Film },
  { match: (s) => s.includes("binocluri") && s.includes("electronice"), Icon: Focus },
  { match: (s) => s.includes("soundbar") || s.includes("media-players"), Icon: Tv },
  { match: (s) => s.includes("televizoare"), Icon: Tv },
  { match: (s) => s.includes("proiectoare") && s.includes("electronice"), Icon: Lightbulb },
  { match: (s) => s.includes("scaun-gaming"), Icon: Sofa },
  {
    match: (s) =>
      (s.includes("smart-becuri") || s.includes("camere-ip") || s.includes("alarme")) && s.includes("electronice"),
    Icon: Home,
  },
  { match: (s) => s.includes("roboti") && s.includes("electronice"), Icon: Package },
  { match: (s) => s.includes("climatizare") && s.includes("electronice"), Icon: Wind },
  { match: (s) => s.includes("electronice-licente") || s.includes("electronice-servicii-it"), Icon: FileText },
  { match: (s) => s.includes("microfoane") && s.includes("electronice"), Icon: Mic2 },
  { match: (s) => s.includes("esapament") || s.includes("transport-esapament"), Icon: Flame },
  { match: (s) => s.includes("remorci-auto") || (s.includes("rulote") && s.includes("transport")), Icon: Truck },
  { match: (s) => s.includes("acustica") && s.includes("transport"), Icon: Radio },
  { match: (s) => s.includes("tractari") && s.includes("transport"), Icon: Truck },
  { match: (s) => s.includes("case-tara"), Icon: Home },
  { match: (s) => s.includes("teren-comercial"), Icon: LandPlot },
  { match: (s) => s.includes("hale-productie"), Icon: Warehouse },
  { match: (s) => s.includes("fotografie-imob"), Icon: Camera },
  { match: (s) => s.includes("scari-usi") || (s.includes("podele") && s.includes("casa")), Icon: DoorOpen },
  { match: (s) => s.includes("piscine") && s.includes("casa"), Icon: Waves },
  { match: (s) => s.includes("irigatii") && s.includes("casa"), Icon: Droplets },
  { match: (s) => s.includes("tablouri-decor"), Icon: Image },
  { match: (s) => s.includes("avocati") || s.includes("juridic"), Icon: FileText },
  { match: (s) => s.includes("contabilitate-serv"), Icon: ClipboardList },
  { match: (s) => s.includes("traduceri"), Icon: BookOpen },
  { match: (s) => s.includes("servicii-medicina"), Icon: Stethoscope },
  { match: (s) => s.includes("servicii-stomatologie"), Icon: Stethoscope },
  { match: (s) => s.includes("instalatii") && s.includes("servicii"), Icon: Wrench },
  { match: (s) => s.includes("retele-it") && s.includes("servicii"), Icon: Wifi },
  { match: (s) => s.includes("marketing") && s.includes("joburi"), Icon: Megaphone },
  { match: (s) => s.includes("livratori") && s.includes("joburi"), Icon: Package },
  { match: (s) => s.includes("curatenie-job"), Icon: Sparkles },
  { match: (s) => s.includes("dulgheri"), Icon: Hammer },
  { match: (s) => s.includes("asistenti") && s.includes("joburi"), Icon: Users },
  { match: (s) => s.includes("profesori"), Icon: BookOpen },
  { match: (s) => s.includes("inot") && s.includes("sport"), Icon: Waves },
  { match: (s) => s.includes("sporturi-acvatice") || s.includes("pescuit"), Icon: Anchor },
  { match: (s) => s.includes("jocuri-societate"), Icon: Puzzle },
  { match: (s) => s.includes("benzi-alergare"), Icon: Dumbbell },
  { match: (s) => s.includes("acvariu"), Icon: Waves },
  { match: (s) => s.includes("reptile"), Icon: Bug },
  { match: (s) => s.includes("pui") && s.includes("agricol"), Icon: Bug },
  { match: (s) => s.includes("pluguri") || (s.includes("irigatii-agro") && s.includes("agricol")), Icon: Shovel },
  { match: (s) => s.includes("marsupii") || (s.includes("patuturi") && s.includes("mama")), Icon: Baby },
  { match: (s) => s.includes("creative") && s.includes("mama"), Icon: Palette },
  { match: (s) => s.includes("hrana-bebelusi"), Icon: Baby },
  { match: (s) => s.includes("textile-pat") && s.includes("mama"), Icon: BedDouble },
  { match: (s) => s.includes("diverse-carti"), Icon: BookOpen },
  { match: (s) => s.includes("diverse-bilete"), Icon: Ticket },
  { match: (s) => s.includes("antichitati"), Icon: Gem },
  { match: (s) => s.includes("textile-sport") && s.includes("moda"), Icon: Shirt },
  { match: (s) => s.includes("scolare") && s.includes("moda"), Icon: ShoppingBag },
  { match: (s) => s.includes("containere") && s.includes("business"), Icon: Package },
  { match: (s) => s.includes("echipamente-bucatarie") && s.includes("business"), Icon: ChefHat },
  { match: (s) => s.includes("rafturi-magazin"), Icon: Store },
  { match: (s) => s.includes("autoturism") || s.includes("epoca"), Icon: Car },
  { match: (s) => s.includes("microbuz") || s.includes("furgon"), Icon: Van },
  /** RO: „camioane” nu conține substringul „camion” */
  { match: (s) => s.includes("camioane") || s.includes("camion"), Icon: Truck },
  { match: (s) => s.includes("autobuz"), Icon: Bus },
  { match: (s) => s.includes("motocic") || s.includes("scuter") || s.includes("biciclete") || s.includes("trotinet"), Icon: Bike },
  { match: (s) => s.includes("atv"), Icon: CarFront },
  { match: (s) => s.includes("barci") || s.includes("ambarcat"), Icon: Anchor },
  { match: (s) => s.includes("electrice") && s.includes("transport"), Icon: Zap },
  { match: (s) => s.includes("tehnica-agricol") || s.includes("tractor") || s.includes("cositoare"), Icon: Construction },
  { match: (s) => s.includes("tehnica-speciala") || s.includes("constructii-mech"), Icon: Construction },
  { match: (s) => s.includes("remorci") || s.includes("rulot"), Icon: Truck },
  { match: (s) => s.includes("anvelope") || s.includes("vulcanizare"), Icon: CircleParking },
  { match: (s) => s.includes("piese-motor"), Icon: Gauge },
  { match: (s) => s.includes("piese-transmisie"), Icon: Settings2 },
  { match: (s) => s.includes("piese-frane"), Icon: Disc },
  { match: (s) => s.includes("piese-suspensie"), Icon: Wrench },
  { match: (s) => s.includes("piese-electrice") || s.includes("instalatie") || (s.includes("electrica") && !s.includes("job")), Icon: Zap },
  { match: (s) => s.includes("piese-caroserie") || s.includes("caroserie-acc"), Icon: DoorOpen },
  { match: (s) => s.includes("filtre") || s.includes("ulei"), Icon: Droplets },
  { match: (s) => s.includes("acc-salon") || s.includes("covoras") || s.includes("covorase"), Icon: Sofa },
  { match: (s) => s.includes("vopsea") && s.includes("transport"), Icon: PaintBucket },
  { match: (s) => s.includes("ajutor-tehnic") || s.includes("tractar"), Icon: Truck },
  { match: (s) => s.includes("chei") || s.includes("cricuri"), Icon: Wrench },
  { match: (s) => s.includes("compresoare"), Icon: Fan },
  { match: (s) => s.includes("diagnostic"), Icon: Scan },
  { match: (s) => s.includes("autoservice") || s.includes("reparatii-auto"), Icon: Wrench },
  { match: (s) => s.includes("transport-marfa") || s.includes("livrare"), Icon: Package },
  { match: (s) => s.includes("inchirieri"), Icon: KeyRound },
  { match: (s) => s.includes("spalatorie") || s.includes("sampon-auto"), Icon: Droplets },
  { match: (s) => s.includes("detergenti") || s.includes("ceara") && s.includes("transport"), Icon: Sparkles },
  { match: (s) => s.includes("smartphone"), Icon: Smartphone },
  { match: (s) => s.includes("telefoane-clasice"), Icon: Phone },
  { match: (s) => s.includes("tablete"), Icon: Tablet },
  { match: (s) => s.includes("smartwatch"), Icon: Watch },
  { match: (s) => s.includes("accesorii-tel"), Icon: Cable },
  { match: (s) => s.includes("laptop"), Icon: Laptop },
  { match: (s) => s.includes("pc-birou"), Icon: Monitor },
  { match: (s) => s.includes("monitoare"), Icon: Monitor },
  { match: (s) => s.includes("componente"), Icon: Cpu },
  { match: (s) => s.includes("periferice"), Icon: Mouse },
  { match: (s) => s.includes("retea"), Icon: Wifi },
  { match: (s) => s.includes("imprimante"), Icon: Printer },
  { match: (s) => s.includes("aparate-foto"), Icon: Camera },
  { match: (s) => s.includes("obiective"), Icon: Focus },
  { match: (s) => s.includes("drona"), Icon: Radio },
  { match: (s) => s.includes("casti") || s.includes("playere"), Icon: Headphones },
  { match: (s) => s.includes("console") || s.includes("jocuri"), Icon: Gamepad2 },
  { match: (s) => s.includes("bucatarie") && s.includes("electronice"), Icon: Refrigerator },
  { match: (s) => s.includes("ingrijire") && s.includes("electronice"), Icon: Bath },
  { match: (s) => s.includes("aspiratoare"), Icon: Wind },
  { match: (s) => s.includes("apartamente"), Icon: Building2 },
  { match: (s) => s.includes("garsoniere") || (s.includes("camere") && s.includes("imob")), Icon: BedDouble },
  { match: (s) => s.includes("case-") || (s.includes("case") && s.includes("imob")), Icon: Home },
  { match: (s) => s.includes("teren"), Icon: LandPlot },
  { match: (s) => s.includes("birouri") && s.includes("imob"), Icon: Building2 },
  { match: (s) => s.includes("spatii-comerciale"), Icon: Store },
  { match: (s) => s.includes("depozite") && s.includes("imob"), Icon: Warehouse },
  { match: (s) => s.includes("hoteluri"), Icon: Hotel },
  { match: (s) => s.includes("garaj") || (s.includes("parcare") && s.includes("imob")), Icon: CircleParking },
  { match: (s) => s.includes("agentii"), Icon: Users },
  { match: (s) => s.includes("evaluari"), Icon: ClipboardList },
  { match: (s) => s.includes("design-interior"), Icon: Palette },
  { match: (s) => s.includes("canapele") || s.includes("dormitor") || (s.includes("mobila") && s.includes("casa")), Icon: Sofa },
  { match: (s) => s.includes("bucatarie-mob"), Icon: ChefHat },
  { match: (s) => s.includes("birou-mob"), Icon: Briefcase },
  { match: (s) => s.includes("depozitare"), Icon: Package },
  { match: (s) => s.includes("materiale"), Icon: Box },
  { match: (s) => s.includes("unelte") && !s.includes("gradina"), Icon: Drill },
  { match: (s) => s.includes("sanitare"), Icon: Bath },
  { match: (s) => s.includes("gips-carton"), Icon: Hammer },
  { match: (s) => s.includes("mobilier-gradina") || s.includes("unelte-gradina"), Icon: Shovel },
  { match: (s) => s.includes("gratar"), Icon: Flame },
  { match: (s) => s.includes("perdele") || s.includes("covor"), Icon: Image },
  { match: (s) => s.includes("luminat"), Icon: Lightbulb },
  { match: (s) => s.includes("zugrav") || s.includes("faianta"), Icon: PaintBucket },
  { match: (s) => s.includes("montaj"), Icon: Hammer },
  { match: (s) => s.includes("site-uri") || s.includes("grafica"), Icon: FileText },
  { match: (s) => s.includes("reparatii-pc"), Icon: Laptop },
  { match: (s) => s.includes("coafor") || s.includes("cosmetic"), Icon: Scissors },
  { match: (s) => s.includes("masaj"), Icon: HeartHandshake },
  { match: (s) => s.includes("curatenie"), Icon: Sparkles },
  { match: (s) => s.includes("spalatorie-textile"), Icon: WashingMachine },
  { match: (s) => s.includes("meditatii") || (s.includes("cursuri") && s.includes("servicii")), Icon: BookOpen },
  { match: (s) => s.includes("foto-video"), Icon: Film },
  { match: (s) => s.includes("evenimente") && s.includes("muzica"), Icon: Mic2 },
  { match: (s) => s.includes("haine") && s.includes("moda"), Icon: Shirt },
  { match: (s) => s.includes("incalt"), Icon: Footprints },
  { match: (s) => s.includes("accesorii") && s.includes("moda"), Icon: ShoppingBag },
  { match: (s) => s.includes("greutati"), Icon: Dumbbell },
  { match: (s) => s.includes("fotbal"), Icon: Disc },
  { match: (s) => s.includes("tenis"), Icon: Disc },
  { match: (s) => s.includes("sporturi-iarna"), Icon: Snowflake },
  { match: (s) => s.includes("corturi"), Icon: Tent },
  { match: (s) => s.includes("drumetii"), Icon: Mountain },
  { match: (s) => s.includes("numismatica"), Icon: BadgePercent },
  { match: (s) => s.includes("machete"), Icon: Puzzle },
  { match: (s) => s.includes("accesorii-caine"), Icon: Dog },
  { match: (s) => s.includes("accesorii-pisica"), Icon: Cat },
  { match: (s) => s.includes("caini"), Icon: Dog },
  { match: (s) => s.includes("pisici"), Icon: Cat },
  { match: (s) => s.includes("pasari") || s.includes("rozatoare"), Icon: Bug },
  { match: (s) => s.includes("flori") || s.includes("pomi"), Icon: Flower2 },
  { match: (s) => s.includes("dresaj"), Icon: PawPrint },
  { match: (s) => s.includes("vet"), Icon: Stethoscope },
  { match: (s) => s.includes("furaje") || s.includes("seminte"), Icon: Sprout },
  { match: (s) => s.includes("vite") || s.includes("oi") || s.includes("porci"), Icon: PiggyBank },
  { match: (s) => s.includes("carucior") || s.includes("scaun-auto"), Icon: Baby },
  { match: (s) => s.includes("jucarii"), Icon: Puzzle },
  { match: (s) => s.includes("carti-copii"), Icon: BookOpen },
  { match: (s) => s.includes("biberoane"), Icon: Baby },
  { match: (s) => s.includes("instrumente") && s.includes("muzica"), Icon: Music },
  { match: (s) => s.includes("echipament-studio"), Icon: Radio },
  { match: (s) => s.includes("tablouri"), Icon: Image },
  { match: (s) => s.includes("handmade"), Icon: PenTool },
  { match: (s) => s.includes("ceasuri"), Icon: Watch },
  { match: (s) => s.includes("bijuterii"), Icon: Gem },
  { match: (s) => s.includes("nedefinit"), Icon: Tag },
  { match: (s) => s.includes("linii-productie"), Icon: Settings2 },
  { match: (s) => s.includes("generatoare"), Icon: Zap },
  { match: (s) => s.includes("stocuri"), Icon: Package },
  { match: (s) => s.includes("administrativ"), Icon: ClipboardList },
  { match: (s) => s.includes("vanzari") && s.includes("job"), Icon: ShoppingBag },
  { match: (s) => s.includes("it-job"), Icon: Laptop },
  { match: (s) => s.includes("contabilitate"), Icon: FileText },
  { match: (s) => s.includes("operator") && s.includes("job"), Icon: Settings2 },
  { match: (s) => s.includes("sofer-job") || (s.includes("soferi") && s.includes("servicii")), Icon: Car },
  { match: (s) => s.includes("depozit") && s.includes("job"), Icon: Warehouse },
  { match: (s) => s.includes("horeca"), Icon: ChefHat },
  { match: (s) => s.includes("retail") && s.includes("job"), Icon: Store },
  { match: (s) => s.includes("ingrijire") && s.includes("servicii-job"), Icon: Users },
  { match: (s) => s.includes("zugrav-job"), Icon: PaintBucket },
  { match: (s) => s.includes("electrician-job"), Icon: Zap },
];

/** Ultimă linie de apărare: icon potrivit secțiunii, nu etichetă generică. */
function iconBySectionPrefix(s: string): LucideIcon | null {
  if (s.startsWith("transport-")) return Car;
  if (s.startsWith("imobiliare-")) return Building2;
  if (s.startsWith("electronice-")) return Cpu;
  if (s.startsWith("casa-")) return Sofa;
  if (s.startsWith("servicii-")) return Wrench;
  if (s.startsWith("joburi-")) return Briefcase;
  if (s.startsWith("animale-")) return PawPrint;
  if (s.startsWith("moda-")) return Shirt;
  if (s.startsWith("sport-")) return Dumbbell;
  if (s.startsWith("agricol-")) return Sprout;
  if (s.startsWith("mama-copil-")) return Baby;
  if (s.startsWith("diverse-")) return Package;
  if (s.startsWith("business-")) return Briefcase;
  return null;
}

export function getSubcategoryLucideIcon(slug: string): LucideIcon {
  const s = slug.toLowerCase();
  for (const { match, Icon } of RULES) {
    if (match(s)) return Icon;
  }
  return iconBySectionPrefix(s) ?? Tag;
}
