/**
 * Liste modele telefon — sursă unică pentru seed DB și fallback static în formular.
 */

export const APPLE_IPHONE_MODELS: readonly string[] = [
  "iPhone 7",
  "iPhone 7 Plus",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone X",
  "iPhone XR",
  "iPhone XS",
  "iPhone XS Max",
  "iPhone 11",
  "iPhone 11 Pro",
  "iPhone 11 Pro Max",
  "iPhone SE (2nd gen)",
  "iPhone 12 mini",
  "iPhone 12",
  "iPhone 12 Pro",
  "iPhone 12 Pro Max",
  "iPhone 13 mini",
  "iPhone 13",
  "iPhone 13 Pro",
  "iPhone 13 Pro Max",
  "iPhone SE (3rd gen)",
  "iPhone 14",
  "iPhone 14 Plus",
  "iPhone 14 Pro",
  "iPhone 14 Pro Max",
  "iPhone 15",
  "iPhone 15 Plus",
  "iPhone 15 Pro",
  "iPhone 15 Pro Max",
  "iPhone 16",
  "iPhone 16 Plus",
  "iPhone 16 Pro",
  "iPhone 16 Pro Max",
  "iPhone 16e",
  "iPhone 17",
  "iPhone 17 Pro",
  "iPhone 17 Pro Max",
  "iPhone Air",
];

export const SAMSUNG_GALAXY_S_MODELS: readonly string[] = [
  "Galaxy S8",
  "Galaxy S8+",
  "Galaxy S9",
  "Galaxy S9+",
  "Galaxy S10e",
  "Galaxy S10",
  "Galaxy S10+",
  "Galaxy S20",
  "Galaxy S20+",
  "Galaxy S20 Ultra",
  "Galaxy S20 FE",
  "Galaxy S21",
  "Galaxy S21+",
  "Galaxy S21 Ultra",
  "Galaxy S21 FE",
  "Galaxy S22",
  "Galaxy S22+",
  "Galaxy S22 Ultra",
  "Galaxy S23",
  "Galaxy S23+",
  "Galaxy S23 Ultra",
  "Galaxy S23 FE",
  "Galaxy S24",
  "Galaxy S24+",
  "Galaxy S24 Ultra",
  "Galaxy S24 FE",
  "Galaxy S25",
  "Galaxy S25+",
  "Galaxy S25 Ultra",
];

export const SAMSUNG_GALAXY_A_MODELS: readonly string[] = [
  "Galaxy A10",
  "Galaxy A12",
  "Galaxy A13",
  "Galaxy A14",
  "Galaxy A15",
  "Galaxy A16",
  "Galaxy A20",
  "Galaxy A21s",
  "Galaxy A22",
  "Galaxy A23",
  "Galaxy A24",
  "Galaxy A25",
  "Galaxy A32",
  "Galaxy A33",
  "Galaxy A34",
  "Galaxy A35",
  "Galaxy A36",
  "Galaxy A40",
  "Galaxy A41",
  "Galaxy A42",
  "Galaxy A50",
  "Galaxy A51",
  "Galaxy A52",
  "Galaxy A53",
  "Galaxy A54",
  "Galaxy A55",
  "Galaxy A56",
  "Galaxy A70",
  "Galaxy A71",
  "Galaxy A72",
  "Galaxy A73",
];

export const SAMSUNG_NOTE_MODELS: readonly string[] = [
  "Galaxy Note 8",
  "Galaxy Note 9",
  "Galaxy Note 10",
  "Galaxy Note 10+",
  "Galaxy Note 20",
  "Galaxy Note 20 Ultra",
];

export const SAMSUNG_Z_MODELS: readonly string[] = [
  "Galaxy Z Fold2",
  "Galaxy Z Fold3",
  "Galaxy Z Fold4",
  "Galaxy Z Fold5",
  "Galaxy Z Fold6",
  "Galaxy Z Fold7",
  "Galaxy Z Flip",
  "Galaxy Z Flip 5G",
  "Galaxy Z Flip3",
  "Galaxy Z Flip4",
  "Galaxy Z Flip5",
  "Galaxy Z Flip6",
  "Galaxy Z Flip7",
];

export function allSamsungPhoneModels(): readonly string[] {
  return [
    ...SAMSUNG_GALAXY_S_MODELS,
    ...SAMSUNG_GALAXY_A_MODELS,
    ...SAMSUNG_NOTE_MODELS,
    ...SAMSUNG_Z_MODELS,
  ];
}
