export const VEHICLE_BRANDS = [
  "Audi",
  "BMW",
  "Chevrolet",
  "Citroen",
  "Dacia",
  "Fiat",
  "Ford",
  "Honda",
  "Hyundai",
  "Kia",
  "Lexus",
  "Mazda",
  "Mercedes-Benz",
  "Mitsubishi",
  "Nissan",
  "Opel",
  "Peugeot",
  "Porsche",
  "Renault",
  "Seat",
  "Skoda",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
] as const;

/** Etichete vehicul: folosiți cheile din messages (ListingForm) și VEHICLE_*_KEYS din listing-form-options. */

export const MOLDOVA_CITIES = [
  "Anenii Noi",
  "Basarabeasca",
  "Briceni",
  "Bucovet",
  "Cahul",
  "Cantemir",
  "Calarasi",
  "Causeni",
  "Ceadir-Lunga",
  "Chisinau",
  "Cimislia",
  "Comrat",
  "Cricova",
  "Criuleni",
  "Cupcini",
  "Donduseni",
  "Drochia",
  "Dubasari",
  "Edinet",
  "Falesti",
  "Floresti",
  "Glodeni",
  "Hincesti",
  "Ialoveni",
  "Leova",
  "Nisporeni",
  "Ocnita",
  "Orhei",
  "Rezina",
  "Riscani",
  "Ribnita",
  "Sangerei",
  "Singerei",
  "Slobozia",
  "Soldanesti",
  "Soroca",
  "Stefan Voda",
  "Straseni",
  "Taraclia",
  "Telenesti",
  "Tighina",
  "Tiraspol",
  "Ungheni",
  "Vadul lui Voda",
] as const;
