import { VEHICLE_BRANDS } from "@/lib/vehicle-taxonomy";

/** Modele comune per marcă (RO-friendly); poți scrie și manual în câmp. */
export const VEHICLE_MODELS_BY_BRAND: Record<string, readonly string[]> = {
  Toyota: [
    "Corolla",
    "Camry",
    "Yaris",
    "Aygo",
    "RAV4",
    "C-HR",
    "Highlander",
    "Land Cruiser",
    "Prius",
    "Hilux",
    "Proace",
    "Avensis",
    "Auris",
    "Verso",
    "bZ4X",
  ],
  Volkswagen: [
    "Golf",
    "Polo",
    "Passat",
    "Jetta",
    "Tiguan",
    "Touareg",
    "Touran",
    "Sharan",
    "Arteon",
    "T-Cross",
    "T-Roc",
    "ID.3",
    "ID.4",
    "Caddy",
    "Transporter",
    "Amarok",
  ],
  Dacia: [
    "Logan",
    "Sandero",
    "Duster",
    "Lodgy",
    "Dokker",
    "Spring",
    "Jogger",
    "Stepway",
    "Pick-Up",
  ],
  BMW: [
    "Seria 1",
    "Seria 2",
    "Seria 3",
    "Seria 4",
    "Seria 5",
    "Seria 6",
    "Seria 7",
    "Seria 8",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "Z4",
    "i3",
    "i4",
    "iX",
    "iX3",
  ],
  "Mercedes-Benz": [
    "Clasa A",
    "Clasa B",
    "Clasa C",
    "Clasa E",
    "Clasa S",
    "CLA",
    "CLS",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "G-Class",
    "SL",
    "SLC",
    "Vito",
    "Viano",
    "Sprinter",
    "EQC",
    "EQE",
    "EQS",
  ],
  Audi: ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "TT", "e-tron"],
  Ford: [
    "Fiesta",
    "Focus",
    "Mondeo",
    "Fusion",
    "Kuga",
    "Puma",
    "EcoSport",
    "Edge",
    "Explorer",
    "Mustang",
    "Ranger",
    "Transit",
    "Tourneo",
    "S-Max",
    "Galaxy",
  ],
  Hyundai: [
    "i10",
    "i20",
    "i30",
    "i40",
    "Elantra",
    "Accent",
    "Tucson",
    "Santa Fe",
    "Kona",
    "Bayon",
    "Ioniq",
    "Ioniq 5",
    "Ioniq 6",
    "Nexo",
  ],
  Kia: [
    "Picanto",
    "Rio",
    "Ceed",
    "XCeed",
    "Stonic",
    "Sportage",
    "Sorento",
    "Niro",
    "EV6",
    "EV9",
    "Carnival",
    "Optima",
    "Stinger",
  ],
  Nissan: [
    "Micra",
    "Note",
    "Juke",
    "Qashqai",
    "X-Trail",
    "Pathfinder",
    "Murano",
    "Leaf",
    "Ariya",
    "Navara",
    "NV200",
    "Primera",
    "Almera",
  ],
  Skoda: ["Fabia", "Scala", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq"],
  Renault: [
    "Clio",
    "Megane",
    "Laguna",
    "Scenic",
    "Captur",
    "Kadjar",
    "Koleos",
    "Twingo",
    "Zoe",
    "Austral",
    "Arkana",
    "Express",
    "Trafic",
    "Master",
  ],
  Peugeot: ["108", "208", "2008", "301", "308", "3008", "408", "508", "5008", "Rifter", "Traveller", "Partner", "Boxer"],
  Mazda: ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-30", "CX-5", "CX-60", "MX-5", "BT-50"],
  Opel: ["Corsa", "Astra", "Insignia", "Mokka", "Crossland", "Grandland", "Combo", "Vivaro", "Movano", "Zafira"],
  Honda: ["Jazz", "Civic", "Accord", "HR-V", "CR-V", "e:Ny1", "Pilot", "Ridgeline"],
  Suzuki: ["Swift", "Ignis", "Vitara", "S-Cross", "Jimny", "SX4", "Baleno"],
  Citroen: ["C1", "C3", "C4", "C5", "Berlingo", "SpaceTourer", "Jumpy", "Jumper"],
  Fiat: ["500", "500X", "500L", "Panda", "Tipo", "Punto", "Doblo", "Ducato"],
  Chevrolet: ["Spark", "Aveo", "Cruze", "Malibu", "Trax", "Equinox", "Captiva", "Camaro", "Silverado"],
  Volvo: ["V40", "V60", "V90", "S60", "S90", "XC40", "XC60", "XC90", "C40"],
  Lexus: ["CT", "IS", "ES", "GS", "LS", "NX", "RX", "UX", "RZ", "LX"],
  Mitsubishi: ["Space Star", "ASX", "Eclipse Cross", "Outlander", "L200", "Pajero"],
  Porsche: ["911", "718", "Panamera", "Macan", "Cayenne", "Taycan"],
  Tesla: ["Model S", "Model 3", "Model X", "Model Y"],
  Seat: ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco"],
};

const BRAND_LOOKUP = new Map<string, string>(
  VEHICLE_BRANDS.map((b) => [b.toLowerCase(), b]),
);

export function normalizeVehicleBrand(input: string): string | null {
  const t = input.trim();
  if (!t) return null;
  const key = t.toLowerCase();
  return BRAND_LOOKUP.get(key) ?? null;
}

export function getModelsForBrand(brandInput: string): readonly string[] {
  const canon = normalizeVehicleBrand(brandInput);
  if (!canon) return [];
  return VEHICLE_MODELS_BY_BRAND[canon] ?? [];
}
